"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
var AbstractMovableObject_1 = require("./classes/AbstractMovableObject");
var Vector_1 = require("./classes/Vector");
var Move_1 = require("./classes/Move");
var AbstractObject_1 = require("./classes/AbstractObject");
var Rotate_1 = require("./classes/Rotate");
var MoveComponent_1 = require("./components/MoveComponent");
var RotateComponent_1 = require("./components/RotateComponent");
var params = new Map();
params.set("Location", new Vector_1.Vector(12, 5));
params.set("Direction", 90);
params.set("DirectionsNumber", 8);
var moveComp = new MoveComponent_1.MoveComponent(new Vector_1.Vector(0, 0), new Vector_1.Vector(10, 0));
var rotateComp = new RotateComponent_1.RotateComponent(10, Math.PI / 180 * 5);
var spaceShip = new AbstractMovableObject_1.AbstractMovableObject(new AbstractObject_1.AbstractObject(params), moveComp, rotateComp);
var moveExecutor = new Move_1.Move(spaceShip);
var rotateExecutor = new Rotate_1.Rotate(spaceShip);
setInterval(function () {
    moveExecutor.Execute();
    rotateExecutor.Execute();
    console.log(spaceShip.getLocation());
}, 1000);
