"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
var AbstractMovableObject_1 = require("./classes/AbstractMovableObject");
var Vector_1 = require("./classes/Vector");
var Move_1 = require("./classes/Move");
var AbstractObject_1 = require("./classes/AbstractObject");
var Rotate_1 = require("./classes/Rotate");
var params = new Map();
params.set("Location", new Vector_1.Vector(12, 5));
params.set("Direction", 90);
params.set("Velocity", new Vector_1.Vector(-7, 3));
params.set("DirectionsNumber", 8);
params.set("Rotation", 10);
params.set("AngularVelocity", 10);
var spaceShip = new AbstractMovableObject_1.AbstractMovableObject(new AbstractObject_1.AbstractObject(params));
var moveExecutor = new Move_1.Move(spaceShip);
var rotateExecutor = new Rotate_1.Rotate(spaceShip);
setInterval(function () {
    moveExecutor.Execute();
    rotateExecutor.Execute();
    console.log(spaceShip.getLocation());
    console.log(params);
}, 1000);
